services:
  local-mongo-db:
    image: mongo:8-noble
    container_name: mongo-db-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })", "--quiet"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - local-mongo-db_data:/data/db
    networks:
      - local-network
    # restart: unless-stopped

  local-message-broker:
    container_name: message-broker-container
    image: rabbitmq:3.13-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - local-message-broker_data:/var/lib/rabbitmq
    networks:
      - local-network
    # restart: unless-stopped

  local-postgres-db:
    container_name: postgres-db-container
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - local-network
    volumes:
      - local-postgres-db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_PORT}:5432"
    # restart: unless-stopped

  local-pgadmin:
    image: dpage/pgadmin4
    container_name: wb-pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - local-pgadmin_data:/var/lib/pgadmin
    depends_on:
      local-postgres-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - local-network

  local-redis-server:
    container_name: redis-server-container
    restart: always
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - local-redis-server_data:/data
    command: redis-server --appendonly no --save "" --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    # restart: unless-stopped

  local-mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=local-mongo-db
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@local-mongo-db:${MONGO_PORT}/admin
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    depends_on:
      local-mongo-db:
        condition: service_healthy
    networks:
      - local-network
    # restart: unless-stopped

  traefik:
    image: traefik:latest
    container_name: traefik-container
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --api.debug=true
      # Включить Dashboard (только для разработки!)
      - --api.insecure=true
      # Включить автоматическое обнаружение Docker-сервисов
      - --providers.docker=true
      - --providers.file.directory=/config
      - --providers.file.watch=true
      # Включить конфигурацию для передачи массива ссылок swagger-ring plugin
      - --providers.file.directory=/config
      - --providers.file.watch=true
      # Логи для отладки
      - --log.level=TRACE
      - --accesslog=true
      - --log.maxsize=1
      # Только явно разрешённые сервисы
      - --providers.docker.exposedbydefault=false
      # Основной HTTP
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --serversTransport.forwardingTimeouts.dialTimeout=15s
      - --serversTransport.forwardingTimeouts.responseHeaderTimeout=15s
      # Enable ACME (Let’s Encrypt) with HTTP challenge
      # - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      # - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      # - --certificatesresolvers.letsencrypt.acme.email=root@mail.ru
      # - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # Ссылка на plugin
      - --experimental.plugins.swagger-ring.moduleName=github.com/usalko/swagger-ring
      - --experimental.plugins.swagger-ring.version=v0.1.9
      - --entrypoints.web.http.middlewares=cors@file
      - --entrypoints.websecure.http.middlewares=cors@file
    ports:
      - "${HTTP_PORT_EXT:-8080}:80"    # Balancer port
      - "${HTTP_PORT_EXT_TA:-8090}:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./swagger-ring-config.yaml:/config/swagger-ring-config.yaml
      - ./cors.yaml:/config/cors.yaml
    networks:
      - local-network

  whoami:
    image: traefik/whoami
    container_name: whoami-container
    # labels:
    #   - "a=streaming"
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.docs-router.rule=PathPrefix(`/api/v1/docs`)"
    #   - "traefik.http.routers.docs-router.service=docs-service"
    #   - "traefik.http.routers.docs-router.entrypoints=web"
    #   - "traefik.http.routers.docs-router.middlewares=swagger"
    #   - "traefik.http.services.docs-service.loadBalancer.server.url=http://whoami"
    #   - "traefik.http.middlewares.swagger.plugin.swagger-ring.path=/api/v1/docs"
    #   - "traefik.http.middlewares.swagger.plugin.swagger-ring.docs[0].path=http://auth-service:${HTTP_PORT:-8002}/api/v1/docs/swagger.yaml"
    networks:
      - local-network

  grafana:
    image: grafana/grafana
    user: root
    restart: always
    ports:
      - 3000:3000
    volumes:
      - local-grafana-data:/var/lib/grafana
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./configs/grafana/dashboards:/etc/grafana/provisioning/dashboards/
    container_name: grafana
    hostname: grafana
    environment:
      TZ: "Europe/Moscow"
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    networks:
      - local-network

  prometheus:
    image: prom/prometheus:v2.42.0
    ports:
      - "9090:9090"
    # Change 127.0.0.1 to ip address of node where docker satck is deployed     
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus" 
      - "--web.external-url=http://127.0.0.1:9090"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries" 
      - "--web.console.templates=/usr/share/prometheus/consoles"
    volumes:
      - local-prom-data:/prometheus
      - ./configs/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - local-network
      

  alertmanager:
    image: prom/alertmanager:v0.25.0
    ports:
      - "9093:9093"
    # Change 127.0.0.1 to ip address of node where docker satck is deployed 
    command: 
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager" 
      - "--web.external-url=http://127.0.0.1:9093"      
    volumes:
      - local-alert-data:/alertmanager
      - ./configs/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./configs/myorg.tmpl:/etc/alertmanager/templates/myorg.tmpl
    networks:
      - local-network
      

  node-exporter:
    image: prom/node-exporter:v1.5.0
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    networks:
      - local-network
      
      
  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:v0.47.0
  #   container_name: cadvisor
  #   ports:
  #   - 8091:8091
  #   volumes:
  #   - /:/rootfs:ro
  #   - /var/run:/var/run:rw
  #   - /sys:/sys:ro
  #   - /var/lib/docker/:/var/lib/docker:ro
  #   networks:
  #     - local-network


volumes:
  local-mongo-db_data:
  local-message-broker_data:
  local-postgres-db_data:
  local-redis-server_data:
  local-pgadmin_data:
  local-grafana-data:
  local-prom-data:
  local-alert-data:


networks:
  local-network:
    driver: bridge 